apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: internship
data:
  SPRING_PROFILES_ACTIVE: "docker"
  SPRING_DATASOURCE_DRIVER: "org.postgresql.Driver"
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://userdb:5432/userservice"
  DOCKER_DATASOURCE_AUTH_URL: "jdbc:postgresql://authdb:5432/authservice"
  SPRING_DATASOURCE_AUTH_USERNAME: "postgres"
  SPRING_ORDER_DATASOURCE_URL: "jdbc:postgresql://orderdb:5432/orderservice"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_MONGODB_URI: "mongodb://mongodb:27017/payment_service_db"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  USER_SERVICE_BASE_URL: "http://userservice:8081"
  DOCKER_USER_SERVICE_BASE_URL: "http://userservice:8081"
  RANDOM_API_URL: "https://www.randomnumberapi.com"
