spring.datasource.url=${DOCKER_DATASOURCE_AUTH_URL}
spring.datasource.username=${SPRING_DATASOURCE_AUTH_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_AUTH_PASSWORD}
services.user-service.base-url=${DOCKER_USER_SERVICE_BASE_URL}