version: '3.8'

services:
  app:
    build: .
    container_name: orderservice
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SPRING_ORDER_DATASOURCE_URL=${SPRING_ORDER_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER}
      - JWT_SECRET=${JWT_SECRET}
      - USER_SERVICE_BASE_URL=${USER_SERVICE_BASE_URL}
    depends_on:
      - orderdb
    restart: unless-stopped

  orderdb:
    image: postgres:16
    container_name: orderservice-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: